##All shoes
GET http://localhost:3011/api/shoes

### Shoe by brand and size
GET http://localhost:3011/api/shoes/brand//size/6

###Shoes by brand 
GET http://localhost:3011/api/shoes/brand/Steve-Madden

### Shoes by size
GET http://localhost:3011/api/shoes/size/7

### Add a shoe
POST  http://localhost:3011/api/admin
Content-Type: application/json

{   
"color": "navy",
"brand": "Adidas",
"price": 1999,
"size": 6,
"in_stock": 5,
"image_url": "https://th.bing.com/th/id/R.7734d8ce719e573ec2117680c5637e09?rik=mBRljcztdn4lpA&pid=ImgRaw&r=0"
   }

### Remove a shoe from stock
POST http://localhost:3011/api/admin/sold
Content-Type: application/json

{   
"id": 2,
"quantity": 3
   }

###DELETE all the shoes from the selected Id
POST http://localhost:3011/api/admin/delete/2

#### Get soldout shoes
GET  http://localhost:3011/api/admin/soldout

### register a user 
POST http://localhost:3011/api/users
Content-Type: application/json

{   
"username": "Londeka",
"password": "password00",
"email": "LK@gmail.com",
"balance": 10000

   }

### add to cart
POST http://localhost:3011/api/users/cart/
Content-Type: application/json

{   
"image_url": "https://th.bing.com/th/id/R.7734d8ce719e573ec2117680c5637e09?rik=mBRljcztdn4lpA&pid=ImgRaw&r=0",
"quantity": 3,
"email": "LK@gmail.com"
   }

### get the cart 
GET http://localhost:3011/api/users/cart/LK@gmail.com
    
####Checkout 
POST http://localhost:3011/api/users/checkout/LK@gmail.com

